services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: money-tracker-api
    ports:
      - "5050:5050"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
